default:
	gcc task1_malloc.c -o task1_malloc.o
	gcc task2_realloc.c -o task2_realloc.o
	gcc task3_list.c -o task3_list.o
	gcc demo_framework.c demo1_leak.c -o demo1_leak.o
	gcc demo_framework.c demo1_fixed.c -o demo1_fixed.o

clean:
	rm *.o
