default:
	gcc task1_fork.c -o task1_fork.o
	gcc task2_exec.c -o task2_exec.o
	gcc task3_threads.c -lpthread -o task3_threads.o
	gcc task3_threads_badret.c -lpthread -o task3_threads_badret.o
	gcc task4_semaphore.c -lpthread -o task4_semaphore.o
	gcc task5_fork.c -lpthread -o task5_fork.o
	gcc task5_pthread.c -lpthread -o task5_pthread.o
	gcc task6.c -o task6.o
	gcc task7.c -o task7.o
	gcc demo1_fork.c -o demo1_fork.o
	gcc demo1_pthread.c -lpthread -o demo1_pthread.o

clean:
	rm *.o
